vich_uploader:
    db_driver: orm

    mappings:
        employee_images:
            uri_prefix:         '%app.path.employee_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.employee_images%'

